<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Definition
</h1>

<p style="font-family: Georgia; font-size: 18px;">
  Numpy stands for numerical python and is the core library for numeric and scientific computing.
    ✅It consists of multi dimensional array objects and a collection of routines for processing those arrarys.</br>
    ✅It makes math fast and simple especailly for scientific and data work</br>
    ✅ Traditional list is slow to mathemtical operation thats why we need numpy library
    
</p>


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Dimensions of Arrays
</h1>




<p style="font-family: Georgia; font-size: 18px;">
    1.<code> 1-Dimensional</code> array just like a list or line</br>
</p>

In [5]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
arr  #notice the change of print(arr) and direct printing

array([1, 2, 3])

<p style="font-family: Georgia; font-size: 18px;">
    2.<code> 2-Dimensional</code>array just like a table (Rows and Columns)</br>
</p>

In [8]:
arr=np.array([[4,9,8],[3,4,5]])
arr

array([[4, 9, 8],
       [3, 4, 5]])

<p style="font-family: Georgia; font-size: 18px;">
    3.<code> 3-Dimensional</code>array like a stack of tables(one table in another table)</br>
    --Think of it like a stack of 2D tables(multiple layers)
</p>

In [9]:
arr=np.array([[[1,2],[3,4],[4,5]]])
arr

array([[[1, 2],
        [3, 4],
        [4, 5]]])

<p style="font-family: Georgia; font-size: 18px;">
    4.<code> 0-Dimensional</code>array is  a single number</br>
</p>

In [11]:
arr=np.array(7)
print(arr)

7


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Common Numpy Functions
</h1>




<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.array</code>-----create an array</br>
</p>

In [13]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


<p style="font-family: Georgia; font-size: 18px;">
    2.<code>np.shape</code>-----get the shape(rows and columns)</br>
</p>

In [18]:
arr=np.array([[3,4],[4,9]])
arr.shape

(2, 2)

<p style="font-family: Georgia; font-size: 18px;">
    3.<code>np.mean()</code>-----average of elements</br>
</p>

In [26]:
arr=np.array([[2,3,4],[5,4,3]])
arr.mean()

3.5

<p style="font-family: Georgia; font-size: 18px;">
    4.<code>np.sum()</code>-----total sum of elements</br>
</p>

In [27]:
arr=np.array([[[3,4,5],[9,3,8],[3,6,9]]])
arr.sum()

50

<p style="font-family: Georgia; font-size: 18px;">
    5.<code>np.arange(a)</code>-----it will give an array of numbers from 0 to a(exclusive) </br>
</p>

In [32]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

<p style="font-family: Georgia; font-size: 18px;">
    5.<code>np.reshape</code>-----change the shape of current array </br>
</p>

In [37]:
arr=np.array([[3,4,5],[4,8,9]])
print(arr.shape)
arr.reshape(3,2)

(2, 3)


array([[3, 4],
       [5, 4],
       [8, 9]])

<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Initializing Numpy with Zeros
</h1>

<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.zeros((a))</code> creates a 1D array of zeros </br>
    2.<code>np.zeros((a,b))</code> creates a 2D array of zeros with </br>
        a= number of rows</br>
    b=number of columns</br>
    3.<code>np.zeros((a,b,c))</code> creates a 3D array of zeros with </br>
    a= number of tables</br>
    b= number of rows</br>
    c=number of columns</br>
    * 0.  means all the numbers are float number(by default)</br> 
    Why use it?</br>
    ⏺️Make an empty structure to fill later</br>
    ⏺️Initialize a matrix before calculation</br>
    ⏺️Avoid random starting values
</p>





In [50]:
arr1=np.zeros((3))
arr2=np.zeros((3,4))
arr3=np.zeros((3,3,4))
print(f'1D Array=\n{arr1}')
print(f'\n 2D Array=\n{arr2}')
print(f'\n 3D Array=\n{arr3}')

1D Array=
[0. 0. 0.]

 2D Array=
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 3D Array=
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Initializing Numpy with Same Number
</h1>

<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.full((a),c)</code> creates <b>1D</b> all elements are <b>c</b>  </br>
    2.<code>np.full((a,b),c)</code> creates <b>2D</b> array of all elements are <b>c</b>  </br>
    3.<code>np.full((a,b),c)</code> creates <b>3D</b> array of all elements are <b>c</b>  </br>
</p>

In [54]:
arr1=np.full((3),10)
print(arr1)

arr2=np.full((3,3),5)
print("\n",arr2 )

arr3=np.full((2,3,4),10)
print("\n",arr3)


[10 10 10]

 [[5 5 5]
 [5 5 5]
 [5 5 5]]

 [[[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]

 [[10 10 10 10]
  [10 10 10 10]
  [10 10 10 10]]]


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Initializing Numpy Array within a range
</h1>

<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.arange(a,b)</code> starts with <b>a(inclusive)</b> ends to <b>b(exclusive)</b> with <b>interval 1</b>  </br>
    2.<code>np.arange(a,b,c)</code> starts with <b>a(inclusive)</b> ends to <b>b(exclusive)</b> with <b>step or interval c</b>  </br>
</p>

In [55]:
arr1 = np.arange(3,10)
print(arr1)

arr2=np.arange(2,40,5)
print(arr2)

[3 4 5 6 7 8 9]
[ 2  7 12 17 22 27 32 37]


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Initializing Numpy Array within a range
</h1>

<p style="font-family: Georgia; font-size: 18px;">
 1.<code>np.random.rand()</code> returns a random float value between 0 and 1 </br>
 2.<code>np.random.rand(2,3)</code> returns a 2 by 3 array with random float numbers</br>
 3.<code>np.random.seed(23)</code> returns the same number of the next random line when we use it with that</br>
 4.<code>np.random.randint(20,30)</code> returns an random  integer value between 20 and 30(exclusive) </br>
 5.<code>np.random.randint(20,30,5)</code> returns 5 random  integer values between 20 and 30(exclusive) </br>
 6.<code>np.random.randint(10, 100, size=(3, 4)))</code> returns a 3 by 4 2D array with numbers between 10 and 100 (exclusive) </br>
 7.<code>np.random.randint(10, 100, size=(3, 4, 5)))</code> returns a  3D array of 3 tables of 4 by 5 size with numbers between 10 and 100 (exclusive) </br>
</p>  

In [74]:
rand1=np.random.rand()
print(rand1)

rand2=np.random.rand(2,3)
print(rand2)

rand4=np.random.randint(20,30)
print(rand4)

rand5=np.random.randint(20,30,5)
print(rand5)


0.08250004969715541
[[0.89709858 0.2980035  0.26230482]
 [0.00512955 0.54320252 0.47559637]]
25
[25 25 28 27 23]


In [79]:
rand3=np.random.seed(43)
rand6=np.random.rand() #this will returns the same float number for each run because we are using seed on it
print(rand6)

0.11505456638977896


In [84]:
rand7=np.random.randint(10,30,size=(2,3))
print(rand7)

rand8=np.random.randint(10,30,size=(2,3,4))
print("\n" ,rand8)

[[27 29 11]
 [15 23 18]]

 [[[10 29 19 14]
  [24 16 22 21]
  [14 14 28 18]]

 [[11 18 19 22]
  [25 15 20 29]
  [14 20 12 13]]]


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Checking Shape of Numpy Array
</h1>

<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.shape</code> check the shape in the form (table,rows,columns) for 3D ,(rows,columns) for 2D and (rows,) for 1D </br>
    2.<code>arr.shape=(a,b)</code> for changing the shape to (a,b)(it is possible) if  a*b=number of elements </br>
    *Notice the shape changing tecnique ,it's important
</p>
      

In [89]:
arr1=np.array([[2,3,4],[7,5,6]])
print(arr1)
print(f'\nOld Shape: {arr1.shape}')

arr1.shape=(6,1)

print("\n",arr1)
print(f'\nNew Shape: {arr1.shape}')

[[2 3 4]
 [7 5 6]]

Old Shape: (2, 3)

 [[2]
 [3]
 [4]
 [7]
 [5]
 [6]]

New Shape: (6, 1)


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
  Joining Numpy Arrays
</h1>

<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.vstack((arr1,arr2))</code> means vertical stack --it stacks arr1 and arr2 on top of each other (like rows in table) </br>
    2.<code>np.hstack((arr1,arr2))</code> means horizontal stack --it stacks arr1 and arr2 side by side  (like adding more columns) </br>
    3.<code>np.column_stack((arr1,arr2))</code> means vertical stack --it stacks 1D arrays to 2D array side by side   where, </br>
   <b> arr1 becomes the first column</b> </br>
   <b> arr2 becomes the second column</b> 
    
    *Notice the changes
</p>
      

In [96]:
arr1=np.array([3,4,5])
arr2=np.array([7,8,6])

vs=np.vstack((arr1,arr2))
print(vs)

hs=np.hstack((arr1,arr2))
print("\n",hs)

cs=np.column_stack((arr1,arr2))
print("\n", cs)

[[3 4 5]
 [7 8 6]]

 [3 4 5 7 8 6]

 [[3 7]
 [4 8]
 [5 6]]


<h1 style="font-family: 'Segoe UI', sans-serif; font-size: 30px; color: #097770;">
 Numpy Intersection and Difference
</h1>

<p style="font-family: Georgia; font-size: 18px;">
    1.<code>np.intersect1d(arr1,arr2)</code> returns common elements of arr1 and arr2 </br>
    2.<code>arr.setdiff1d(arr1,arr2)</code> returns the elements of arr1 which are not common in arr2 </br>
    *for 1D arrays
</p>
      

In [97]:
arr1=np.array([2,3,4,6,7])
arr2=np.array([9,8,2,4,7])

intersect=np.intersect1d(arr1,arr2) 
print(intersect)

diff=np.setdiff1d(arr1,arr2)
print("\n",diff)

[2 4 7]

 [3 6]
